### Normalization

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

X = np.array([[10], [20], [30], [40], [100]])
scaler = MinMaxScaler(feature_range=(0,1))
X_transformed = scaler.fit_transform(X)

print(X_transformed)


[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [1.        ]]


### Z-score Normalization

In [2]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X = np.array([[10], [20], [30], [40], [100]])

X_transformed = scaler.fit_transform(X)

print(X_transformed)

[[-0.9486833 ]
 [-0.63245553]
 [-0.31622777]
 [ 0.        ]
 [ 1.8973666 ]]


### Decimal Scaling Normalization

In [6]:
X = np.array([[10], [20], [30], [40], [-100]])

j = len(str(np.max(np.abs(X))))
X_transformed = X/10**j
print(X_transformed)

[[ 0.01]
 [ 0.02]
 [ 0.03]
 [ 0.04]
 [-0.1 ]]


In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cities = ['Kathmandu', 'Pokhara', 'Biratnagar']
encoded = le.fit_transform(cities)

print(encoded)

[1 2 0]


## Feature Encoding One hot encoding

In [8]:
import pandas as pd

df = pd.DataFrame({'source': ['river', 'lake', 'well']})
df_encoded = pd.get_dummies(df, columns=['source'])

print(df_encoded)

   source_lake  source_river  source_well
0        False          True        False
1         True         False        False
2        False         False         True


## Ordinal encoding

In [13]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[['poor', 'fair', 'good']])
quality = [['poor'], ['good'], ['fair']]
encoded = encoder.fit_transform(quality)

print(encoded)

[[0.]
 [2.]
 [1.]]


In [25]:
import numpy as np
import time

X = np.random.random(10000000)
print(X[:5])
start = time.time()
for i in range(X.shape[0]):
    X[i] = X[i] + 2
end = time.time()    
print(X[:5]) 
print(f'Time taken is {end-start} second')   

[0.91418946 0.70529397 0.57997018 0.67427535 0.15613344]
[2.91418946 2.70529397 2.57997018 2.67427535 2.15613344]
Time taken is 2.324352979660034 second


In [24]:
import numpy as np
import time

X = np.random.random(10000000)
print(X[:5])
start = time.time()
X = X + 2
end = time.time()    
print(X[:5]) 
print(f'Time taken is {end-start} second')   

[0.14425766 0.69509971 0.88421555 0.7287008  0.29028153]
[2.14425766 2.69509971 2.88421555 2.7287008  2.29028153]
Time taken is 0.0337519645690918 second
